### ISSUE TITLE
Scale: server could not find the requested resource

### ISSUE THREAD

**Issue by mathieuduperre** [GoogleCloudPlatform/agones#646] opened 2019-03-13 13:25 UTC
Follwing the simple-udp example, when trying to scale a fleet, we get the message:
Error from server (NotFound): the server could not find the requested resource (get fleets simple-udp)

Even though we have such fleet. Self-installed k8 in a vm (gcp), versions below. 

[root@agones simple-udp]# kubectl get fleet
NAME         SCHEDULING   DESIRED   CURRENT   ALLOCATED   READY   AGE
simple-udp   Packed       2         2         0           2       33s

[root@agones simple-udp]# kubectl get gs
NAME                     STATE   ADDRESS       PORT   NODE     AGE
simple-udp-59rmx-lqk9j   Ready   10.150.0.16   7555   agones   36s
simple-udp-59rmx-qbvd5   Ready   10.150.0.16   7177   agones   36s

[root@agones simple-udp]# kubectl scale fleet simple-udp --replicas=3
**Error from server (NotFound): the server could not find the requested resource (get fleets simple-udp)
[root@agones simple-udp]#**

[root@agones simple-udp]# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by markmandel** [comment] 2019-03-13 16:17
What version of Agones are you running?

I'm not sure if anyone has tested Agones post 1.11 at the moment. I wonder if there is something different in 1.13?

What happens if you try 1.11 or 1.12? (I haven't tested 1.12 yet)

**Comment by markmandel** [comment] 2019-03-13 16:19
Also, how are you bootstrapping this Kubernetes cluster? Are we sure that this is a valid Kubernetes install?

**Comment by mathieuduperre** [comment] 2019-03-13 21:06
I was running 0.7.0, upgrading to 0.8.0 did not do it. reinstalling with k8 1.11 and will re-try. 

this is a vanilla k8 on centos 7 with a single node as master/tainted to run pods. I can run everything else fine (including open match and our own components).  i'll report back with 1.11

**Comment by markmandel** [comment] 2019-03-13 21:50
> vanilla k8 on centos 7

kubeadm? How did you bootstrap it?

What happens if you edit the fleet instead of using scale? (Wondering if this is somehow an rbac issue? or you are referencing a different namespace somehow?)

**Comment by mathieuduperre** [comment] 2019-03-14 13:54
Re-installed and had the same issue. I'm using kubeadm. 
Editing the fleet manually (kubectl edit) worked. 
I'll do some more test later as we're just starting to integrate with Agones but it could be something we're doing wrong with our k8 install.  We used kubeadm init with very few args, so unless the default config yaml has something weird I don't see what could be missing.  Standby i should be able to dig that one up after GDC.

**Comment by markmandel** [comment] 2019-03-14 15:45
Are you using the [recommended set of admission controllers](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#is-there-a-recommended-set-of-admission-controllers-to-use)?

**Comment by aLekSer** [comment] 2019-03-18 11:17
@mathieuduperre I am trying to reproduce this issue. Can you please give some steps on how to create such a cluster?

**Comment by mathieuduperre** [comment] 2019-03-18 12:15
@aLekSer Below are the exact steps. high level steps:

centos 7 vm in gcp
install kubelet, kubeadm, docker using standard doc:
https://kubernetes.io/docs/tasks/tools/install-kubectl/
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

install flannel to get basic networking
taint the node to run pods in the master (single node cluster to test)
install agones using the yaml (including the cluster role binding)
starting a fleet works, using scale did not. 



`


yum -y update

 cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF


cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kube*
EOF


yum install -y kubectl kubelet kubeadm docker git
systemctl enable docker
systemctl enable kubelet
systemctl start docker

setenforce 0
sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

# your vm internal ip
kubeadm init --apiserver-advertise-address=1.2.3.4 --pod-network-cidr=10.244.0.0/16

kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
kubectl get nodes
kubectl taint node agones1 node-role.kubernetes.io/master:NoSchedule-
kubectl create clusterrolebinding cluster-admin-binding   --clusterrole=cluster-admin --serviceaccount=kube-system:default
kubectl create namespace agones-system
kubectl apply -f https://github.com/GoogleCloudPlatform/agones/raw/release-0.7.0/install/yaml/install.yaml
git clone https://github.com/GoogleCloudPlatform/agones.git
cd agones/examples/simple-udp/
kubectl create -f gameserver.yaml
kubectl get gs
vi gameserver.yaml   # You have to replace Dynamic with dynamic
kubectl get gs
kubectl create -f gameserver.yaml
kubectl get gs
kubectl delete gs simple-udp-7scrz
kubectl create -f fleet.yaml
kubectl get fleet
kubectl get gs
kubectl scale fleet simple-udp --replicas=3
kubectl get fleets simple-udp

`

**Comment by aLekSer** [comment] 2019-03-18 13:35
@mathieuduperre I have reproduced the same error message.
The reason is that you have deployed version 0.7.0 of agones which does not support Scale subresource for fleet.
```
kubectl apply -f https://github.com/GoogleCloudPlatform/agones/raw/release-0.7.0/install/yaml/install.yaml
```
However there is an error in docs, which stated to use `kubectl scale --replicas=n` which is suppoted only starting from 0.8.0-rc.
https://0-7-0.agones.dev/site/docs/getting-started/create-fleet/

**Comment by aLekSer** [comment] 2019-03-18 13:49
The original way how to do this in 0.7.0 version was:
```
Run `kubectl edit fleet simple-udp`, which will open an editor for you to edit the Fleet configuration.
Scroll down to the `spec > replicas` section, and change the values of `replicas: 2` to `replicas: 5`.
Save the file and exit - this will apply the changes.
```
https://github.com/GoogleCloudPlatform/agones/blob/625728ef5f24675cfba4c702f0ca87dc6d9bdea7/site/content/en/docs/Getting%20Started/create-fleet.md
Or you can use:
```
 kubectl apply -f https://github.com/GoogleCloudPlatform/agones/raw/release-0.8.0/install/yaml/install.yam
```
However using new version (0.8.0) I got another error:
```
$ kubectl apply -f ../examples/simple-udp/fleet.yaml                                                                                                             
fleet.stable.agones.dev/simple-udp2 created
$ kubectl scale --replicas 2 fleet simple-udp2                                                                                                                   
error: could not find proper group-version for scale subresource of stable.agones.dev/v1alpha1, Resource=fleets: could not find scale subresource for stable.agones.dev/v1alpha1, Resource=fleets in discovery information
```

**Comment by markmandel** [comment] 2019-04-12 20:34
Can we close this now? I don't think we could reproduce?

**Closed** 2019-04-14 11:54 UTC
Labels: kind/bug, question
