### ISSUE TITLE
Move to go modules

### ISSUE THREAD

**Issue by markmandel** [GoogleCloudPlatform/agones#625] opened 2019-02-26 23:31 UTC
Apparently [Go Modules](https://github.com/golang/go/wiki/Modules) are a thing now :smile: and where Go is headingin the near future (1.13 I think they will be default).

We should convert over from dep to the modules at some point in the future.

**Comment by heartrobotninja** [comment] 2019-02-26 23:38
I will be working on this shortly.

**Comment by aLekSer** [comment] 2019-02-27 08:32
@heartrobotninja  Please don't forget about #414 which currently was manually fixed in /vendor
https://github.com/kubernetes/kubernetes/pull/70277 is merged, but not sure about target Kubernetes version.

**Comment by aLekSer** [comment] 2019-03-04 11:40
@heartrobotninja  also note that we can have use vendors with modules at the same time to mitigate mentioned above issue:
https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away

**Comment by heartrobotninja** [comment] 2019-03-08 18:26
Here is what we have so far: 

Moving straight to go modules is ideal, but not doable right now. We have code in vendor that contains a fix that will not be released until March 25th, and there is no guarantee when the platforms will update to 1.14 since they are still on 1.12. 

Given this, it might be best that we move to go modules while also keeping the vendor directory. This would require re-implementing the fix from #414. If we are ok with doing that, I can do both parts fairly quickly.

**Comment by markmandel** [comment] 2019-03-08 18:47
It sounds like a way forward, but what does "_re-implementing the fix_" entail? Just making sure it's pasted into the new vendor directory?

Question - with go modules,without a vendor directory, does that mean on each CI build, we would have to download all our dependencies every time?

**Comment by heartrobotninja** [comment] 2019-03-08 19:13
re-implementing would just be re-applying the fix. I know there is a cache for go modules, but I am currently trying to hunt down how that works with CI builds.

**Comment by markmandel** [comment] 2019-03-08 19:17
Gotcha. We'd likely want to store that in GCS and move it back and forth.

**Comment by heartrobotninja** [comment] 2019-03-08 20:52
As for CI:
We could either cache all dependencies prior to building. This still makes us download still, but we do it in advance of building. There might be some magic we can do there where we keep the cache warmed. 

The other option is doing module-aware vendoring. This is mostly what we do now, so will likely consist of the least changes. Both are supported and I would propose we just do module-aware vendoring for now.

**Comment by markmandel** [comment] 2019-03-08 21:37
> I would propose we just do module-aware vendoring for now.

SGTM 👍

**Comment by heartrobotninja** [comment] 2019-03-11 02:10
Currently have modules working for LOCAL_GO=true. Currently working out some issues with the non-local version failing. Been looking into why this would be a problem for docker run.

**Comment by heartrobotninja** [comment] 2019-03-12 19:55
What I am currently running into: The intermediate containers which get instantiated by RUN aren't inheriting environment variables.

**Comment by heartrobotninja** [comment] 2019-03-12 20:19
So, the go.mod file isn't visible in the intermediate container. That is the actual problem.

**Comment by heartrobotninja** [comment] 2019-03-15 03:53
I finally have gotten things to get past the missing mod file, but now I am trying to sort through the differences in local vs docker because while local building works fine, docker has some issues finding certain packages. The current one is:
build agones.dev/agones/cmd/controller: cannot load k8s.io/api/admissionregistration/v1alpha1: cannot find module providing package k8s.io/api/admissionregistration/v1alpha1

**Comment by heartrobotninja** [comment] 2019-03-15 04:59
Its apparently by design per https://github.com/kubernetes/client-go/issues/551 they removed v1alpha1 from master, but we still have an indirect dependency on it via an import of an import.

**Comment by heartrobotninja** [comment] 2019-03-15 06:36
Fun fact, when running go build as we do for build-controller-binary, I can't get the build to recognize that a go.mod file exists unless I put a command before go build. For instance if I put pwd && go build -mod=vendor it works.

**Comment by heartrobotninja** [comment] 2019-03-15 23:00
Progress! I have make build and make test working. I need to do some e2e testing and documentation and I will have a pull ready.

**Comment by heartrobotninja** [comment] 2019-03-16 06:18
e2e testing worked. Fixing some issues with the gen-grpc files that have cropped up due to vendoring.

**Comment by heartrobotninja** [comment] 2019-03-16 23:06
Design Doc:
[https://goo.gl/uNhtJ2](https://goo.gl/uNhtJ2)

**Comment by markmandel** [comment] 2019-04-01 21:17
Can this be closed now?

**Comment by heartrobotninja** [comment] 2019-04-01 21:33
Yep!

**Closed** 2019-04-01 21:35 UTC
Labels: area/build-tools, help wanted, kind/cleanup

**Comment by roberthbailey** [comment] 2019-04-17 16:37
Should the GOPATH section of the build/README be removed (or updated) in light of this change or is is still necessary to install inside of GOPATH for IDE integration?
