### ISSUE TITLE
Slow game servers deletion

### ISSUE THREAD

**Issue by Kuqd** [GoogleCloudPlatform/agones#540] opened 2019-01-31 16:35 UTC
If you create a fleet using the tutorial command :

```
kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/agones/release-0.7.0/examples/simple-udp/fleet.yaml
```

Then over provision (say 40 replica) the fleet using `kubectl edit` a lot of pods will get stuck in scheduling.

However if you delete the fleet, it disappears instantly, pods will be delete within seconds but gameservers can stay for up to 10min hanging before ultimately disappearing.

We should investigate what is the root cause of this.

**Comment by markmandel** [comment] 2019-01-31 16:40
Oh that's fun. I'm almost willing to bet that what happens is:

1. GameServer has a finaliser
1. The finaliser only gets removed when the `GamerServer`'s backing pod gets deleted
1. Since they are stuck in `Scheduling` there will be no pod until there is room
1. So it takes time to create the Pod and then have it removed

So we should look at if when you delete a GameServer, remove the finaliser if it's at Scheduled or before. (Possible concern with race conditions - but that should be the general gist)

**Comment by jkowalski** [comment] 2019-01-31 16:55
I thought we have to release the port regardless?

**Comment by Kuqd** [comment] 2019-01-31 16:58
Something that I'd appreciate, we only delete the fleet only when replica is down to 0, WDYT ?

**Comment by markmandel** [comment] 2019-01-31 17:01
@jkowalski 

So the port only physically gets released once the Pod is gone -- hence the finaliser.

At PortAllocated - we assign a port from our in memory registry of available ports - but we don't do anything to lock a specific port at that stage physically on the network.

So if we delete the GameServer before the Pod goes up, the PortAllocator will just free up the port in the registry, and make it available again.

@Kuqd you can always do this yourself by doing a `foregroundDeletion` ([details](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#controlling-how-the-garbage-collector-deletes-dependents)) - although not sure how to do that from kubectl.

**Comment by Kuqd** [comment] 2019-01-31 19:39
@markmandel I'll give a try to foregroundDeletion, it's for an API.

**Comment by Kuqd** [comment] 2019-01-31 21:36
I tried `foregroundDeletion` and it's worst, it's never ending, seems that there is a race between creating an deleting gs/pods.

**Comment by ilkercelikyilmaz** [comment] 2019-02-14 18:51
I believe this issue is also resolved (which was similar to issue #543) I tested and it seems fine (I tested by creating 4000 GS). Can someone else confirm it so we can close. I believe recent GSS and Delete improvements resolved the issue.

**Comment by Kuqd** [comment] 2019-02-15 14:19
I'll investigate.

**Comment by jkowalski** [comment] 2019-03-01 19:35
@Kuqd can we close now?

**Comment by markmandel** [comment] 2019-03-17 17:48
Gentle bump - @Kuqd can we close this now?

**Comment by markmandel** [comment] 2019-03-25 17:13
I'm going to close this, please feel free to reopen if it rears its head again.

**Closed by markmandel** 2019-03-25 17:13 UTC
Labels: area/performance

**Comment by tenevdev** [comment] 2021-07-06 13:51
Hello, I'd like to reopen this, specifically the part about foreground deletion. I can reproduce it with agones 1.14.0 and a fleet which has 2 or more replicas - it keeps deleting and starting new game servers in a loop. Maybe there is some work to do in order to stop creating replicas for a fleet when it has a finalizer / deletion timestamp?

**Comment by markmandel** [comment] 2021-07-07 17:18
@tenevdev can you create a new issue, with reproducible steps that are run against the latest Agones?

I think this is hard to track exactly what your issue is otherwise, as this ticket wandered a little from its original intent.
