### ISSUE TITLE
Fleet status completely out-of-sync with GameServerSet status

### ISSUE THREAD

**Issue by jkowalski** [GoogleCloudPlatform/agones#570] opened 2019-02-07 17:35 UTC
This is when running a test that scales fleets up and down. The numbers observed by fleet should be roughly in sync with corresponding GSS, but they are not:

```shell
$ kubectl get fleet,gss

NAME                                          SCHEDULING   DESIRED   CURRENT   ALLOCATED   READY   AGE
fleet.stable.agones.dev/scale-fleet-0-pw776   Packed       0         54        0           54      3m
fleet.stable.agones.dev/scale-fleet-1-dsdm9   Packed       0         200       0           200     3m
fleet.stable.agones.dev/scale-fleet-2-skhfw   Packed       0         0         0           0       3m
fleet.stable.agones.dev/scale-fleet-3-ggb2w   Packed       0         200       0           200     3m
fleet.stable.agones.dev/scale-fleet-4-v2v86   Packed       0         47        0           47      3m
fleet.stable.agones.dev/scale-fleet-5-hfshp   Packed       0         200       0           200     3m
fleet.stable.agones.dev/scale-fleet-6-vwqzp   Packed       200       0         0           0       3m
fleet.stable.agones.dev/scale-fleet-7-2vtzh   Packed       0         200       0           200     3m
fleet.stable.agones.dev/scale-fleet-8-b8kgl   Packed       0         99        0           99      2m
fleet.stable.agones.dev/scale-fleet-9-tlnss   Packed       0         200       0           200     2m

NAME                                                        SCHEDULING   DESIRED   CURRENT   ALLOCATED   READY   AGE
gameserverset.stable.agones.dev/scale-fleet-0-pw776-v5h2z   Packed       0         0         0           0       3m
gameserverset.stable.agones.dev/scale-fleet-1-dsdm9-d7vdn   Packed       200       200       0           200     3m
gameserverset.stable.agones.dev/scale-fleet-2-skhfw-krq98   Packed       0         0         0           0       3m
gameserverset.stable.agones.dev/scale-fleet-3-ggb2w-m8s8w   Packed       0         189       0           189     3m
gameserverset.stable.agones.dev/scale-fleet-4-v2v86-2c84s   Packed       0         0         0           0       3m
gameserverset.stable.agones.dev/scale-fleet-5-hfshp-4ztcw   Packed       200       200       0           200     3m
gameserverset.stable.agones.dev/scale-fleet-6-vwqzp-8hb6s   Packed       0         0         0           0       3m
gameserverset.stable.agones.dev/scale-fleet-7-2vtzh-j9tl5   Packed       200       200       0           200     2m
gameserverset.stable.agones.dev/scale-fleet-8-b8kgl-9vcfz   Packed       0         0         0           0       2m
gameserverset.stable.agones.dev/scale-fleet-9-tlnss-fkrqm   Packed       0         35        0           35      2m
```

Simple repro is in PR #571

**Comment by aLekSer** [comment] 2019-02-18 13:28
What I have noticed after running stress-test-e2e with stress factor of 2 :
```
fleet.stable.agones.dev/scale-fleet-1-mfd8s   Packed       20        18        0           0         3m   
gameserverset.stable.agones.dev/scale-fleet-1-mfd8s-9gl9r   Packed       0         16        0           0         3m  
```
After several seconds:
```
fleet.stable.agones.dev/scale-fleet-1-mfd8s   Packed       20        16        0           0         3m
gameserverset.stable.agones.dev/scale-fleet-1-mfd8s-9gl9r   Packed       20        36        0           0         3m 
```
It seems that updating desired count results in adding the Desired to Current Replicas in Gameserversets

**Comment by Yingxin-Jiang** [comment] 2019-02-21 21:50
I will work on this issue.

**Comment by aLekSer** [comment] 2019-02-22 13:06
Hello @Yingxin-Jiang ,
I was thinking of making fleets status updates a bit faster and updating them using `GameServer`  Status, not `GameServerSet` Status. Change in `updateFleetStatus()` from `ListGameServerSetsByFleetOwner()` to `ListGameServersByFleetOwner()`.
Currently we update GS status -> GSS -> then Fleet.

https://github.com/aLekSer/agones/commit/1c3f9924b1eee51f8ffd95a9cb1af8e2d85038c1
But them are not 100% in sync either. I think cause of workerqueues which started in different points in time.

**Comment by Yingxin-Jiang** [comment] 2019-02-25 23:13
@aLekSer Thanks for the info. Looks like you are working on the issue. So I better leave it to you to avoid duplicate work :)

**Comment by aLekSer** [comment] 2019-02-26 08:21
@Yingxin-Jiang , I stopped working on it for a bit, because I was not able to find root cause and how we can sync them. So please, if you have any ideas raise your own fix for this ticket.

**Comment by Yingxin-Jiang** [comment] 2019-02-26 19:05
@aLekSer Thanks again for the info. Then I will give it a try.

**Comment by Yingxin-Jiang** [comment] 2019-02-28 23:17
I can't reproduce the issue. Probably it's fixed by commit https://github.com/GoogleCloudPlatform/agones/commit/f6daaf1fe6092a012fb38385203b1856512de700

**Comment by aLekSer** [comment] 2019-03-01 15:00
Running `stress-test-e2e` with `STRESS_TEST_LEVEL ?= 2` differs only for small amount of time and then got synced in seconds. And amount of Current GameServers never raise above desired 20 GameServers.
![get fleets gss](https://user-images.githubusercontent.com/5626814/53646183-9b772000-3c4b-11e9-9b70-5f385884a7d3.png)

**Comment by markmandel** [comment] 2019-03-01 17:32
Sounds like we can close this issue - and if it pops up again, reopen it?

**Closed** 2019-03-01 19:34 UTC
Labels: good first issue, help wanted, kind/bug
